### ISSUE TITLE
是否支持将一个整体工程中的cpp类，都封装成python？

### ISSUE THREAD

**Issue by ChunelFeng** [charlotteLive/pybind11-Chinese-docs#3]
作者你好，最近想通过 pybind 将这个工程中的各个模块，都封装成python版本的类 https://github.com/ChunelFeng/CGraph 

看了文档介绍，感觉更多的还是去封装一个单独的class文件。

有没有什么好的方法，可以封装工程中，较多的class内容。
其中，还包含了很多的模板类信息

**Comment by charlotteLive** [comment]
pybind11是支持在一个工程中封装多个类的，可以将C++库中需要对外暴露的类用pybind11封一层，再链接C++库即可。

```C++
#include "your_class_header.h"   // class Cat, class Dog

PYBIND11_MODULE(example, m) {
    pybind11::class_<Cat>(m, "Cat");
    pybind11::class_<Dog>(m, "Dog");
}
```

**Comment by charlotteLive** [comment]
模板这方面，pybind11也没提出比较优雅的解决方案。因为C++模板是在编译期实例化的，pybind11不能绑定一个未实例化的模板类或函数。

下面是新版pybind11文档中的描述：

Binding classes with template parameters
pybind11 can also wrap classes that have template parameters. Consider these classes:
```c++
struct Cat {};
struct Dog {};

template <typename PetType>
struct Cage {
    Cage(PetType& pet);
    PetType& get();
};
```

C++ templates may only be instantiated at compile time, so pybind11 can only wrap instantiated templated classes. You cannot wrap a non-instantiated template:
```c++
// BROKEN (this will not compile)
py::class_<Cage>(m, "Cage");
    .def("get", &Cage::get);
```
You must explicitly specify each template/type combination that you want to wrap separately.
```c++
// ok
py::class_<Cage<Cat>>(m, "CatCage")
    .def("get", &Cage<Cat>::get);

// ok
py::class_<Cage<Dog>>(m, "DogCage")
    .def("get", &Cage<Dog>::get);
```

stackoverflow提供的一种处理方式：[Template metafunctions to generate pybind11 bindings](https://stackoverflow.com/questions/55867708/template-metafunctions-to-generate-pybind11-bindings)

**Comment by ChunelFeng** [comment]
了解了，感谢您的指教
