### ISSUE TITLE
[Feature Request] 考虑部署到网页中

### ISSUE THREAD

**Issue by Social-Mean** [charlotteLive/pybind11-Chinese-docs#4]
这个项目很棒!

是否考虑过部署到网页中? markdown 格式的文档可以借助 mdbook 轻松地部署到 github.io 的网站上.

类似于 [《Effective Modern C++ 》翻译](https://cntransgroup.github.io/EffectiveModernCppChinese/).

参考资料:
[mdBook 文档](https://rust-lang.github.io/mdBook/)
[《Effective Modern C++ 》翻译仓库的自动部署的workflow](https://github.com/CnTransGroup/EffectiveModernCppChinese/blob/master/.github/workflows/deploy.yml)

**Comment by charlotteLive** [comment]
感谢，已添加mdBook自动部署
